-- GENERATED FILE - do not edit by hand.
-- Built by tools/build_bis_data.py from:
--   [WotLK] BiS Lists for 3.3.5a end game.xlsx
-- Regenerate with:  python tools/build_bis_data.py
--
-- 27 specs, 452 best-in-slot items, 163 alternatives.
-- Entries without an item id (no link in the workbook) are resolved by
-- name through AtlasLoot at runtime:
--   Protection Paladin: Libram of the Eternal Tower
--   Elemental Shaman: Totem of Hex

RaidInspectorBiSData = {
    source = "[WotLK] BiS Lists for 3.3.5a end game.xlsx",
    specs = {
        {
            key = "blood-dk-tank",
            label = "Blood DK Tank",
            class = "DEATHKNIGHT",
            role = "Tanks",
            items = {
                { slot = "Head", ilvl = 277, id = 50640, name = "Broken Ram Skull Helm" },
                { slot = "Neck", ilvl = 277, id = 50682, name = "Bile-Encrusted Medallion",
                    alts = {
                        { ilvl = 277, id = 50627, name = "Noose of Malachite" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51309, name = "Sanctified Scourgelord Pauldrons" },
                { slot = "Back", ilvl = 277, id = 50718, name = "Royal Crimson Cloak",
                    alts = {
                        { ilvl = 264, id = 50466, name = "Sentinel's Winter Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51305, name = "Sanctified Scourgelord Chestguard" },
                { slot = "Wrist", ilvl = 264, id = 51901, name = "Gargoyle Spit Bracers",
                    alts = {
                        { ilvl = 277, id = 50611, name = "Bracers of Dark Reckoning" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51307, name = "Sanctified Scourgelord Handguards" },
                { slot = "Waist", ilvl = 264, id = 50991, name = "Verdigris Chain Belt",
                    alts = {
                        { ilvl = 277, id = 50691, name = "Belt of Broken Bones" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51308, name = "Sanctified Scourgelord Legguards",
                    alts = {
                        { ilvl = 277, id = 50612, name = "Legguards of Lost Hope" },
                    },
                },
                { slot = "Feet", ilvl = 284, id = 54579, name = "Treads of Impending Resurrection",
                    alts = {
                        { ilvl = 277, id = 50625, name = "Grinning Skull Greatboots" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50622, name = "Devium's Eternally Cold Ring" },
                { slot = "Ring", ilvl = 277, id = 50642, name = "Juggernaut Band",
                    alts = {
                        { ilvl = 277, id = 50404, name = "Ashen Band of Endless Courage" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50364, name = "Sindragosa's Flawless Fang" },
                { slot = "Trinket", ilvl = 284, id = 54591, name = "Petrified Twilight Scale",
                    alts = {
                        { ilvl = 258, id = 47451, name = "Juggernaut's Vitality" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 49623, name = "Shadowmourne",
                    alts = {
                        { ilvl = 284, id = 50730, name = "Glorenzelg, High-Blade of the Silver Hand" },
                    },
                },
                { slot = "Sigil", ilvl = 245, id = 47672, name = "Sigil of Insolence",
                    alts = {
                        { ilvl = 150, id = 40822, name = "Sigil of the Frozen Conscience" },
                    },
                },
            },
        },
        {
            key = "unholy-dk",
            label = "Unholy DK",
            class = "DEATHKNIGHT",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51312, name = "Sanctified Scourgelord Helmet" },
                { slot = "Neck", ilvl = 284, id = 54581, name = "Penumbra Pendant",
                    alts = {
                        { ilvl = 277, id = 50647, name = "Ahn'kahar Onyx Neckguard" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51314, name = "Sanctified Scourgelord Shoulderplates" },
                { slot = "Back", ilvl = 277, id = 50677, name = "Winding Sheet" },
                { slot = "Chest", ilvl = 277, id = 51310, name = "Sanctified Scourgelord Battleplate" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50659, name = "Polar Bear Claw Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51311, name = "Sanctified Scourgelord Gauntlets" },
                { slot = "Waist", ilvl = 277, id = 50620, name = "Coldwraith Links" },
                { slot = "Legs", ilvl = 277, id = 50624, name = "Scourge Reaver's Legplates" },
                { slot = "Feet", ilvl = 284, id = 54578, name = "Apocalypse's Advance",
                    alts = {
                        { ilvl = 277, id = 50639, name = "Blood-Soaked Saronite Stompers" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50693, name = "Might of Blight" },
                { slot = "Ring", ilvl = 277, id = 52572, name = "Ashen Band of Endless Might" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will",
                    alts = {
                        { ilvl = 284, id = 54576, name = "Signet of Twilight" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale",
                    alts = {
                        { ilvl = 258, id = 47464, name = "Death's Choice" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 49623, name = "Shadowmourne",
                    alts = {
                        { ilvl = 284, id = 50730, name = "Glorenzelg, High-Blade of the Silver Hand" },
                    },
                },
                { slot = "Sigil", ilvl = 264, id = 50459, name = "Sigil of the Hanged Man",
                    alts = {
                        { ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings *" },
                    },
                },
            },
        },
        {
            key = "frost-dk",
            label = "Frost DK",
            class = "DEATHKNIGHT",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51312, name = "Sanctified Scourgelord Helmet" },
                { slot = "Neck", ilvl = 284, id = 54581, name = "Penumbra Pendant",
                    alts = {
                        { ilvl = 277, id = 50647, name = "Ahn'kahar Onyx Neckguard" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51314, name = "Sanctified Scourgelord Shoulderplates" },
                { slot = "Back", ilvl = 277, id = 47548, name = "Garrosh's Rage" },
                { slot = "Chest", ilvl = 277, id = 51310, name = "Sanctified Scourgelord Battleplate" },
                { slot = "Wrist", ilvl = 277, id = 50670, name = "Toskk's Maximized Wristguards",
                    alts = {
                        { ilvl = 277, id = 50659, name = "Polar Bear Claw Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50675, name = "Aldriana's Gloves of Secrecy" },
                { slot = "Waist", ilvl = 277, id = 50620, name = "Coldwraith Links" },
                { slot = "Legs", ilvl = 277, id = 51126, name = "Sanctified Scourgelord Legplates" },
                { slot = "Feet", ilvl = 284, id = 54578, name = "Apocalypse's Advance",
                    alts = {
                        { ilvl = 277, id = 50639, name = "Blood-Soaked Saronite Stompers" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50693, name = "Might of Blight" },
                { slot = "Ring", ilvl = 277, id = 52572, name = "Ashen Band of Endless Might" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings" },
                { slot = "Off Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings" },
                { slot = "Sigil", ilvl = 213, id = 40207, name = "Sigil of Awareness" },
            },
        },
        {
            key = "feral-cat",
            label = "Feral Cat",
            class = "DRUID",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51296, name = "Sanctified Lasherweave Headguard" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51299, name = "Sanctified Lasherweave Shoulderpads" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak",
                    alts = {
                        { ilvl = 272, id = 47546, name = "Sylvanas' Cunning *" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51298, name = "Sanctified Lasherweave Raiment" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50670, name = "Toskk's Maximized Wristguards" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50675, name = "Aldriana's Gloves of Secrecy" },
                { slot = "Waist", ilvl = 277, id = 50707, name = "Astrylian's Sutured Cinch" },
                { slot = "Legs", ilvl = 277, id = 51297, name = "Sanctified Lasherweave Legguards" },
                { slot = "Feet", ilvl = 277, id = 50607, name = "Frostbitten Fur Boots" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight",
                    alts = {
                        { ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50604, name = "Band of the Bone Colossus",
                    alts = {
                        { ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring *" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50735, name = "Oathbinder, Charge of the Ranger-General" },
                { slot = "Idol", ilvl = 264, id = 50456, name = "Idol of the Crying Moon" },
            },
        },
        {
            key = "bear",
            label = "Bear",
            class = "DRUID",
            role = "Tanks",
            items = {
                { slot = "Head", ilvl = 277, id = 51296, name = "Sanctified Lasherweave Headguard" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51299, name = "Sanctified Lasherweave Shoulderpads" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak",
                    alts = {
                        { ilvl = 272, id = 47546, name = "Sylvanas' Cunning *" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51298, name = "Sanctified Lasherweave Raiment" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50670, name = "Toskk's Maximized Wristguards" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50675, name = "Aldriana's Gloves of Secrecy" },
                { slot = "Waist", ilvl = 277, id = 50707, name = "Astrylian's Sutured Cinch" },
                { slot = "Legs", ilvl = 277, id = 51297, name = "Sanctified Lasherweave Legguards" },
                { slot = "Feet", ilvl = 277, id = 50607, name = "Frostbitten Fur Boots" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight",
                    alts = {
                        { ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50604, name = "Band of the Bone Colossus",
                    alts = {
                        { ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring *" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50364, name = "Sindragosa's Flawless Fang" },
                { slot = "Trinket", ilvl = 258, id = 47451, name = "Juggernaut's Vitality" },
                { slot = "Main Hand", ilvl = 284, id = 50735, name = "Oathbinder, Charge of the Ranger-General" },
                { slot = "Idol", ilvl = 264, id = 50456, name = "Idol of the Crying Moon" },
            },
        },
        {
            key = "balance-druid",
            label = "Balance Druid",
            class = "DRUID",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51290, name = "Sanctified Lasherweave Cover" },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51292, name = "Sanctified Lasherweave Mantle" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51294, name = "Sanctified Lasherweave Vestment" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51291, name = "Sanctified Lasherweave Gloves",
                    alts = {
                        { ilvl = 277, id = 50663, name = "Gunship Captain's Mittens" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Idol", ilvl = 264, id = 50457, name = "Idol of the Lunar Eclipse" },
            },
        },
        {
            key = "restoration-druid",
            label = "Restoration Druid",
            class = "DRUID",
            role = "Healers",
            items = {
                { slot = "Head", ilvl = 277, id = 51302, name = "Sanctified Lasherweave Helmet" },
                { slot = "Neck", ilvl = 277, id = 50609, name = "Bone Sentinel's Amulet" },
                { slot = "Shoulders", ilvl = 277, id = 51304, name = "Sanctified Lasherweave Pauldrons" },
                { slot = "Back", ilvl = 277, id = 50668, name = "Greatcloak of the Turned Champion" },
                { slot = "Chest", ilvl = 277, id = 50717, name = "Sanguine Silk Robes" },
                { slot = "Wrist", ilvl = 284, id = 54584, name = "Phaseshifter's Bracers",
                    alts = {
                        { ilvl = 277, id = 50630, name = "Bracers of Eternal Dreaming" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51301, name = "Sanctified Lasherweave Gauntlets",
                    alts = {
                        { ilvl = 277, id = 50615, name = "Handguards of Winter's Respite" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50705, name = "Professor's Bloodied Smock" },
                { slot = "Legs", ilvl = 277, id = 51303, name = "Sanctified Lasherweave Legplates" },
                { slot = "Feet", ilvl = 277, id = 50665, name = "Boots of Unnatural Growth",
                    alts = {
                        { ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50636, name = "Memory of Malygos",
                    alts = {
                        { ilvl = 277, id = 50400, name = "Ashen Band of Endless Wisdom" },
                    },
                },
                { slot = "Ring", ilvl = 284, id = 54585, name = "Ring of Phased Regeneration" },
                { slot = "Trinket", ilvl = 277, id = 50366, name = "Althor's Abacus",
                    alts = {
                        { ilvl = 226, id = 47432, name = "Solace of the Fallen" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54589, name = "Glowing Twilight Scale",
                    alts = {
                        { ilvl = 187, id = 37111, name = "Soul Preserver" },
                    },
                },
                { slot = "Main Hand", ilvl = 245, id = 46017, name = "Val'anyr, Hammer of Ancient Kings",
                    alts = {
                        { ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                    },
                },
                { slot = "Off Hand", ilvl = 277, id = 50635, name = "Sundial of Eternal Dusk",
                    alts = {
                        { ilvl = 277, id = 50685, name = "Trauma *" },
                    },
                },
                { slot = "Idol", ilvl = 264, id = 50454, name = "Idol of the Black Willow" },
            },
        },
        {
            key = "marksman-hunter",
            label = "Marksman Hunter",
            class = "HUNTER",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51286, name = "Sanctified Ahn'Kahar Blood Hunter's Headpiece" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51288, name = "Sanctified Ahn'Kahar Blood Hunter's Spaulders" },
                { slot = "Back", ilvl = 272, id = 47546, name = "Sylvanas' Cunning",
                    alts = {
                        { ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51289, name = "Sanctified Ahn'Kahar Blood Hunter's Tunic" },
                { slot = "Wrist", ilvl = 277, id = 50655, name = "Scourge Hunter's Vambraces" },
                { slot = "Hands", ilvl = 277, id = 51285, name = "Sanctified Ahn'Kahar Blood Hunter's Handguards" },
                { slot = "Waist", ilvl = 277, id = 50688, name = "Nerub'ar Stalker's Cord" },
                { slot = "Legs", ilvl = 277, id = 50645, name = "Leggings of Northern Lights" },
                { slot = "Feet", ilvl = 284, id = 54577, name = "Returning Footfalls" },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance",
                    alts = {
                        { ilvl = 284, id = 54576, name = "Signet of Twilight" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring *" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50735, name = "Oathbinder, Charge of the Ranger-General" },
                { slot = "Crossbow", ilvl = 284, id = 50733, name = "Fal'inrush, Defender of Quel'thalas",
                    alts = {
                        { ilvl = 277, id = 50638, name = "Zod's Repeating Longbow" },
                    },
                },
            },
        },
        {
            key = "survival-hunter",
            label = "Survival Hunter",
            class = "HUNTER",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51286, name = "Sanctified Ahn'Kahar Blood Hunter's Headpiece" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51288, name = "Sanctified Ahn'Kahar Blood Hunter's Spaulders" },
                { slot = "Back", ilvl = 272, id = 47546, name = "Sylvanas' Cunning",
                    alts = {
                        { ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51289, name = "Sanctified Ahn'Kahar Blood Hunter's Tunic" },
                { slot = "Wrist", ilvl = 277, id = 50655, name = "Scourge Hunter's Vambraces" },
                { slot = "Hands", ilvl = 277, id = 51285, name = "Sanctified Ahn'Kahar Blood Hunter's Handguards" },
                { slot = "Waist", ilvl = 277, id = 50688, name = "Nerub'ar Stalker's Cord" },
                { slot = "Legs", ilvl = 277, id = 50645, name = "Leggings of Northern Lights" },
                { slot = "Feet", ilvl = 284, id = 54577, name = "Returning Footfalls" },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50735, name = "Oathbinder, Charge of the Ranger-General" },
                { slot = "Crossbow", ilvl = 284, id = 50733, name = "Fal'inrush, Defender of Quel'thalas",
                    alts = {
                        { ilvl = 277, id = 50638, name = "Zod's Repeating Longbow" },
                    },
                },
            },
        },
        {
            key = "ttw-fire-mage",
            label = "TTW Fire Mage",
            class = "MAGE",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51281, name = "Sanctified Bloodmage Hood" },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51284, name = "Sanctified Bloodmage Shoulderpads" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 50629, name = "Robe of the Waking Nightmare" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51280, name = "Sanctified Bloodmage Gloves",
                    alts = {
                        { ilvl = 277, id = 50663, name = "Gunship Captain's Mittens" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt",
                    alts = {
                        { ilvl = 277, id = 50702, name = "Lingering Illness" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51282, name = "Sanctified Bloodmage Leggings" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich" },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50732, name = "Bloodsurge, Kel'Thuzad's Blade of Agony" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "arcane-mage",
            label = "Arcane Mage",
            class = "MAGE",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51281, name = "Sanctified Bloodmage Hood" },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51284, name = "Sanctified Bloodmage Shoulderpads" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51283, name = "Sanctified Bloodmage Robe" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51280, name = "Sanctified Bloodmage Gloves" },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50732, name = "Bloodsurge, Kel'Thuzad's Blade of Agony" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "retribution-paladin",
            label = "Retribution Paladin",
            class = "PALADIN",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51277, name = "Sanctified Lightsworn Helmet" },
                { slot = "Neck", ilvl = 284, id = 54581, name = "Penumbra Pendant",
                    alts = {
                        { ilvl = 277, id = 50647, name = "Ahn'kahar Onyx Neckguard" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51279, name = "Sanctified Lightsworn Shoulderplates" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak",
                    alts = {
                        { ilvl = 277, id = 50677, name = "Winding Sheet" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51275, name = "Sanctified Lightsworn Battleplate" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50659, name = "Polar Bear Claw Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50619, name = "Anub'ar Stalker's Gloves",
                    alts = {
                        { ilvl = 277, id = 50690, name = "Fleshrending Gauntlets" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50707, name = "Astrylian's Sutured Cinch",
                    alts = {
                        { ilvl = 277, id = 50688, name = "Nerub'ar Stalker's Cord" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51278, name = "Sanctified Lightsworn Legplates" },
                { slot = "Feet", ilvl = 284, id = 54578, name = "Apocalypse's Advance",
                    alts = {
                        { ilvl = 277, id = 50639, name = "Blood-Soaked Saronite Stompers" },
                    },
                },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight",
                    alts = {
                        { ilvl = 277, id = 50678, name = "Seal of Many Mouths" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance",
                    alts = {
                        { ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring *" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50706, name = "Tiny Abomination in a Jar",
                    alts = {
                        { ilvl = 277, id = 50363, name = "Deathbringer's Will (BiS rets are allowed to roll for it)" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 49623, name = "Shadowmourne",
                    alts = {
                        { ilvl = 284, id = 50735, name = "Oathbinder, Charge of the Ranger-General" },
                    },
                },
                { slot = "Libram", ilvl = 245, id = 47661, name = "Libram of Valiance",
                    alts = {
                        { ilvl = 264, id = 50455, name = "Libram of Three Truths" },
                    },
                },
            },
        },
        {
            key = "protection-paladin",
            label = "Protection Paladin",
            class = "PALADIN",
            role = "Tanks",
            items = {
                { slot = "Head", ilvl = 277, id = 51266, name = "Sanctified Lightsworn Faceguard",
                    alts = {
                        { ilvl = 277, id = 50640, name = "Broken Ram Skull Helm" },
                    },
                },
                { slot = "Neck", ilvl = 277, id = 50682, name = "Bile-Encrusted Medallion",
                    alts = {
                        { ilvl = 277, id = 50627, name = "Noose of Malachite" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51269, name = "Sanctified Lightsworn Shoulderguards" },
                { slot = "Back", ilvl = 277, id = 50718, name = "Royal Crimson Cloak",
                    alts = {
                        { ilvl = 264, id = 50466, name = "Sentinel's Winter Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51265, name = "Sanctified Lightsworn Chestguard" },
                { slot = "Wrist", ilvl = 264, id = 51901, name = "Gargoyle Spit Bracers",
                    alts = {
                        { ilvl = 277, id = 50611, name = "Bracers of Dark Reckoning" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51267, name = "Sanctified Lightsworn Handguards" },
                { slot = "Waist", ilvl = 264, id = 50991, name = "Verdigris Chain Belt",
                    alts = {
                        { ilvl = 277, id = 50691, name = "Belt of Broken Bones" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 50612, name = "Legguards of Lost Hope",
                    alts = {
                        { ilvl = 277, id = 51268, name = "Sanctified Lightsworn Legguards" },
                    },
                },
                { slot = "Feet", ilvl = 284, id = 54579, name = "Treads of Impending Resurrection",
                    alts = {
                        { ilvl = 277, id = 50625, name = "Grinning Skull Greatboots" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50622, name = "Devium's Eternally Cold Ring" },
                { slot = "Ring", ilvl = 277, id = 50642, name = "Juggernaut Band",
                    alts = {
                        { ilvl = 277, id = 50404, name = "Ashen Band of Endless Courage" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50364, name = "Sindragosa's Flawless Fang" },
                { slot = "Trinket", ilvl = 284, id = 54591, name = "Petrified Twilight Scale",
                    alts = {
                        { ilvl = 258, id = 47451, name = "Juggernaut's Vitality" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings",
                    alts = {
                        { ilvl = 284, id = 50738, name = "Mithrios, Bronzebeard's Legacy" },
                    },
                },
                { slot = "Shield", ilvl = 277, id = 50729, name = "Icecrown Glacial Wall" },
                { slot = "Libram", ilvl = 245, name = "Libram of the Eternal Tower",
                    alts = {
                        { ilvl = 245, id = 47661, name = "Libram of Valiance" },
                    },
                },
            },
        },
        {
            key = "holy-paladin",
            label = "Holy Paladin",
            class = "PALADIN",
            role = "Healers",
            items = {
                { slot = "Head", ilvl = 277, id = 51272, name = "Sanctified Lightsworn Headpiece" },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50700, name = "Holiday's Grace" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51273, name = "Sanctified Lightsworn Spaulders" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 50680, name = "Rot-Resistant Breastplate" },
                { slot = "Wrist", ilvl = 284, id = 54584, name = "Phaseshifter's Bracers" },
                { slot = "Hands", ilvl = 277, id = 50650, name = "Fallen Lord's Handguards" },
                { slot = "Waist", ilvl = 284, id = 54587, name = "Split Shape Belt",
                    alts = {
                        { ilvl = 277, id = 50671, name = "Belt of the Blood Nova" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants",
                    alts = {
                        { ilvl = 277, id = 50623, name = "Leggings of Dying Candles" },
                    },
                },
                { slot = "Feet", ilvl = 284, id = 54586, name = "Foreshadow Steps",
                    alts = {
                        { ilvl = 277, id = 50632, name = "Boots of the Funeral March" },
                    },
                },
                { slot = "Ring", ilvl = 284, id = 54585, name = "Ring of Phased Regeneration",
                    alts = {
                        { ilvl = 277, id = 50610, name = "Marrowgar's Frigid Eye" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 46051, name = "Meteorite Crystal",
                    alts = {
                        { ilvl = 226, id = 47432, name = "Solace of the Fallen" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54589, name = "Glowing Twilight Scale",
                    alts = {
                        { ilvl = 187, id = 37111, name = "Soul Preserver" },
                    },
                },
                { slot = "Main Hand", ilvl = 245, id = 46017, name = "Val'anyr, Hammer of Ancient Kings",
                    alts = {
                        { ilvl = 284, id = 50732, name = "Bloodsurge, Kel'Thuzad's Blade of Agony" },
                    },
                },
                { slot = "Shield", ilvl = 277, id = 50616, name = "Bulwark of Smouldering Steel" },
                { slot = "Libram", ilvl = 200, id = 40705, name = "Libram of Renewal",
                    alts = {
                        { ilvl = 245, id = 47662, name = "Libram of Veracity" },
                    },
                },
            },
        },
        {
            key = "shadow-priest",
            label = "Shadow Priest",
            class = "PRIEST",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51255, name = "Sanctified Crimson Acolyte Cowl" },
                { slot = "Neck", ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy",
                    alts = {
                        { ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51257, name = "Sanctified Crimson Acolyte Mantle" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51259, name = "Sanctified Crimson Acolyte Raiments" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51256, name = "Sanctified Crimson Acolyte Handwraps",
                    alts = {
                        { ilvl = 277, id = 50663, name = "Gunship Captain's Mittens" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "holy-priest",
            label = "Holy Priest",
            class = "PRIEST",
            role = "Healers",
            items = {
                { slot = "Head", ilvl = 277, id = 51261, name = "Sanctified Crimson Acolyte Hood" },
                { slot = "Neck", ilvl = 277, id = 50609, name = "Bone Sentinel's Amulet" },
                { slot = "Shoulders", ilvl = 277, id = 51264, name = "Sanctified Crimson Acolyte Shoulderpads" },
                { slot = "Back", ilvl = 277, id = 50668, name = "Greatcloak of the Turned Champion" },
                { slot = "Chest", ilvl = 277, id = 50717, name = "Sanguine Silk Robes" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50686, name = "Death Surgeon's Sleeves" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51260, name = "Sanctified Crimson Acolyte Gloves" },
                { slot = "Waist", ilvl = 277, id = 50702, name = "Lingering Illness",
                    alts = {
                        { ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51262, name = "Sanctified Crimson Acolyte Leggings" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50636, name = "Memory of Malygos" },
                { slot = "Ring", ilvl = 284, id = 54585, name = "Ring of Phased Regeneration" },
                { slot = "Trinket", ilvl = 277, id = 50366, name = "Althor's Abacus",
                    alts = {
                        { ilvl = 226, id = 47432, name = "Solace of the Fallen" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54589, name = "Glowing Twilight Scale",
                    alts = {
                        { ilvl = 187, id = 37111, name = "Soul Preserver" },
                    },
                },
                { slot = "Main Hand", ilvl = 245, id = 46017, name = "Val'anyr, Hammer of Ancient Kings",
                    alts = {
                        { ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                    },
                },
                { slot = "Off Hand", ilvl = 277, id = 50635, name = "Sundial of Eternal Dusk" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike",
                    alts = {
                        { ilvl = 277, id = 50631, name = "Nightmare Ender" },
                    },
                },
            },
        },
        {
            key = "discipline-priest",
            label = "Discipline Priest",
            class = "PRIEST",
            role = "Healers",
            items = {
                { slot = "Head", ilvl = 277, id = 51261, name = "Sanctified Crimson Acolyte Hood" },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50700, name = "Holiday's Grace" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51264, name = "Sanctified Crimson Acolyte Shoulderpads" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51259, name = "Sanctified Crimson Acolyte Raiments *" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50686, name = "Death Surgeon's Sleeves" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51260, name = "Sanctified Crimson Acolyte Gloves",
                    alts = {
                        { ilvl = 277, id = 50722, name = "San'layn Ritualist Gloves *" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                { slot = "Legs", ilvl = 277, id = 51262, name = "Sanctified Crimson Acolyte Leggings" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent" },
                { slot = "Ring", ilvl = 284, id = 54585, name = "Ring of Phased Regeneration" },
                { slot = "Trinket", ilvl = 277, id = 50366, name = "Althor's Abacus" },
                { slot = "Trinket", ilvl = 284, id = 54589, name = "Glowing Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "combat-rogue",
            label = "Combat Rogue",
            class = "ROGUE",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51252, name = "Sanctified Shadowblade Helmet" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51254, name = "Sanctified Shadowblade Pauldrons" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak",
                    alts = {
                        { ilvl = 272, id = 47546, name = "Sylvanas' Cunning" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 50656, name = "Ikfirus's Sack of Wonder" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50670, name = "Toskk's Maximized Wristguards" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50675, name = "Aldriana's Gloves of Secrecy" },
                { slot = "Waist", ilvl = 277, id = 50707, name = "Astrylian's Sutured Cinch" },
                { slot = "Legs", ilvl = 277, id = 50697, name = "Gangrenous Leggings" },
                { slot = "Feet", ilvl = 277, id = 50607, name = "Frostbitten Fur Boots" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight",
                    alts = {
                        { ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring *" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings",
                    alts = {
                        { ilvl = 277, id = 50672, name = "Bloodvenom Blade" },
                    },
                },
                { slot = "Off Hand", ilvl = 277, id = 50654, name = "Scourgeborne Waraxe" },
                { slot = "Crossbow", ilvl = 284, id = 50733, name = "Fal'inrush, Defender of Quel'thalas" },
            },
        },
        {
            key = "assassination-rogue",
            label = "Assassination Rogue",
            class = "ROGUE",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 50713, name = "Geistlord's Punishment Sack" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 50646, name = "Cultist's Bloodsoaked Spaulders" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak" },
                { slot = "Chest", ilvl = 277, id = 50656, name = "Ikfirus's Sack of Wonder" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands" },
                { slot = "Hands", ilvl = 277, id = 51251, name = "Sanctified Shadowblade Gauntlets" },
                { slot = "Waist", ilvl = 277, id = 50707, name = "Astrylian's Sutured Cinch" },
                { slot = "Legs", ilvl = 277, id = 51253, name = "Sanctified Shadowblade Legplates" },
                { slot = "Feet", ilvl = 277, id = 50607, name = "Frostbitten Fur Boots" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight" },
                { slot = "Ring", ilvl = 277, id = 50604, name = "Band of the Bone Colossus" },
                { slot = "Trinket", ilvl = 277, id = 50706, name = "Tiny Abomination in a Jar" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50736, name = "Heaven's Fall, Kryss of a Thousand Lies" },
                { slot = "Off Hand", ilvl = 277, id = 50621, name = "Lungbreaker" },
                { slot = "Crossbow", ilvl = 284, id = 50733, name = "Fal'inrush, Defender of Quel'thalas" },
            },
        },
        {
            key = "restoration-shaman",
            label = "Restoration Shaman",
            class = "SHAMAN",
            role = "Healers",
            items = {
                { slot = "Head", ilvl = 277, id = 51247, name = "Sanctified Frost Witch's Headpiece",
                    alts = {
                        { ilvl = 277, id = 50626, name = "Snowstorm Helm" },
                    },
                },
                { slot = "Neck", ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker",
                    alts = {
                        { ilvl = 277, id = 50700, name = "Holiday's Grace" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51245, name = "Sanctified Frost Witch's Spaulders",
                    alts = {
                        { ilvl = 277, id = 50698, name = "Horrific Flesh Epaulets" },
                    },
                },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51249, name = "Sanctified Frost Witch's Tunic",
                    alts = {
                        { ilvl = 277, id = 50723, name = "Mail of Crimson Coins" },
                    },
                },
                { slot = "Wrist", ilvl = 284, id = 54584, name = "Phaseshifter's Bracers",
                    alts = {
                        { ilvl = 277, id = 50687, name = "Bloodsunder's Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 54560, name = "Changeling Gloves",
                    alts = {
                        { ilvl = 277, id = 50703, name = "Unclean Surgical Gloves" },
                    },
                },
                { slot = "Waist", ilvl = 284, id = 54587, name = "Split Shape Belt",
                    alts = {
                        { ilvl = 277, id = 50671, name = "Belt of the Blood Nova" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51246, name = "Sanctified Frost Witch's Legguards" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots",
                    alts = {
                        { ilvl = 277, id = 50652, name = "Necrophotic Greaves" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50400, name = "Ashen Band of Endless Wisdom" },
                    },
                },
                { slot = "Ring", ilvl = 284, id = 54585, name = "Ring of Phased Regeneration",
                    alts = {
                        { ilvl = 277, id = 50610, name = "Marrowgar's Frigid Eye" },
                    },
                },
                { slot = "Trinket", ilvl = 226, id = 47432, name = "Solace of the Fallen",
                    alts = {
                        { ilvl = 187, id = 37111, name = "Soul Preserver" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54589, name = "Glowing Twilight Scale",
                    alts = {
                        { ilvl = 277, id = 50366, name = "Althor's Abacus" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II",
                    alts = {
                        { ilvl = 245, id = 46017, name = "Val'anyr, Hammer of Ancient Kings" },
                    },
                },
                { slot = "Shield", ilvl = 277, id = 50616, name = "Bulwark of Smouldering Steel" },
                { slot = "Totem", ilvl = 264, id = 50464, name = "Totem of the Surging Sea",
                    alts = {
                        { ilvl = 245, id = 47665, name = "Totem of Calming Tides" },
                    },
                },
            },
        },
        {
            key = "elemental-shaman",
            label = "Elemental Shaman",
            class = "SHAMAN",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51237, name = "Sanctified Frost Witch's Helm",
                    alts = {
                        { ilvl = 277, id = 50626, name = "Snowstorm Helm" },
                    },
                },
                { slot = "Neck", ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                { slot = "Shoulders", ilvl = 277, id = 51235, name = "Sanctified Frost Witch's Shoulderpads",
                    alts = {
                        { ilvl = 277, id = 50698, name = "Horrific Flesh Epaulets" },
                    },
                },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51239, name = "Sanctified Frost Witch's Hauberk" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50687, name = "Bloodsunder's Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51238, name = "Sanctified Frost Witch's Gloves" },
                { slot = "Waist", ilvl = 284, id = 54587, name = "Split Shape Belt",
                    alts = {
                        { ilvl = 277, id = 50671, name = "Belt of the Blood Nova" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51236, name = "Sanctified Frost Witch's Kilt" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots",
                    alts = {
                        { ilvl = 277, id = 50652, name = "Necrophotic Greaves" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                { slot = "Shield", ilvl = 277, id = 50616, name = "Bulwark of Smouldering Steel" },
                { slot = "Totem", ilvl = 213, name = "Totem of Hex" },
            },
        },
        {
            key = "enhancement-shaman",
            label = "Enhancement Shaman",
            class = "SHAMAN",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51242, name = "Sanctified Frost Witch's Faceguard" },
                { slot = "Neck", ilvl = 277, id = 50633, name = "Sindragosa's Cruel Claw" },
                { slot = "Shoulders", ilvl = 277, id = 51240, name = "Sanctified Frost Witch's Shoulderguards" },
                { slot = "Back", ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak" },
                { slot = "Chest", ilvl = 277, id = 51244, name = "Sanctified Frost Witch's Chestguard" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50655, name = "Scourge Hunter's Vambraces" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50619, name = "Anub'ar Stalker's Gloves" },
                { slot = "Waist", ilvl = 277, id = 50688, name = "Nerub'ar Stalker's Cord" },
                { slot = "Legs", ilvl = 277, id = 51241, name = "Sanctified Frost Witch's War-Kilt" },
                { slot = "Feet", ilvl = 277, id = 50711, name = "Treads of the Wasteland" },
                { slot = "Ring", ilvl = 277, id = 50604, name = "Band of the Bone Colossus",
                    alts = {
                        { ilvl = 284, id = 54576, name = "Signet of Twilight" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will",
                    alts = {
                        { ilvl = 264, id = 50355, name = "Herkuml War Token" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale",
                    alts = {
                        { ilvl = 277, id = 50706, name = "Tiny Abomination in a Jar" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings" },
                { slot = "Off Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings" },
                { slot = "Totem", ilvl = 264, id = 50458, name = "Bizuri's Totem of Shattered Ice" },
            },
        },
        {
            key = "spellhancement",
            label = "Spellhancement",
            class = "SHAMAN",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51242, name = "Sanctified Frost Witch's Faceguard" },
                { slot = "Neck", ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                { slot = "Shoulders", ilvl = 277, id = 51240, name = "Sanctified Frost Witch's Shoulderguards" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk" },
                { slot = "Chest", ilvl = 277, id = 51244, name = "Sanctified Frost Witch's Chestguard" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands" },
                { slot = "Hands", ilvl = 277, id = 50619, name = "Anub'ar Stalker's Gloves" },
                { slot = "Waist", ilvl = 284, id = 54587, name = "Split Shape Belt" },
                { slot = "Legs", ilvl = 277, id = 51241, name = "Sanctified Frost Witch's War-Kilt" },
                { slot = "Feet", ilvl = 277, id = 50711, name = "Treads of the Wasteland" },
                { slot = "Ring", ilvl = 284, id = 54576, name = "Signet of Twilight" },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale",
                    alts = {
                        { ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich *" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50734, name = "Royal Scepter of Terenas II" },
                { slot = "Off Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings" },
                { slot = "Totem", ilvl = 264, id = 50458, name = "Bizuri's Totem of Shattered Ice" },
            },
        },
        {
            key = "demonology-warlock",
            label = "Demonology Warlock",
            class = "WARLOCK",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51231, name = "Sanctified Dark Coven Hood" },
                { slot = "Neck", ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy" },
                { slot = "Shoulders", ilvl = 277, id = 51234, name = "Sanctified Dark Coven Shoulderpads" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51233, name = "Sanctified Dark Coven Robe" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51230, name = "Sanctified Dark Coven Gloves",
                    alts = {
                        { ilvl = 277, id = 50663, name = "Gunship Captain's Mittens" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt",
                    alts = {
                        { ilvl = 277, id = 50702, name = "Lingering Illness" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50732, name = "Bloodsurge, Kel'Thuzad's Blade of Agony" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "affliction-warlock",
            label = "Affliction Warlock",
            class = "WARLOCK",
            role = "Ranged Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51231, name = "Sanctified Dark Coven Hood" },
                { slot = "Neck", ilvl = 277, id = 50658, name = "Amulet of the Silent Eulogy",
                    alts = {
                        { ilvl = 277, id = 50724, name = "Blood Queen's Crimson Choker" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51234, name = "Sanctified Dark Coven Shoulderpads" },
                { slot = "Back", ilvl = 284, id = 54583, name = "Cloak of Burning Dusk",
                    alts = {
                        { ilvl = 277, id = 50628, name = "Frostbinder's Shredded Cape" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51233, name = "Sanctified Dark Coven Robe" },
                { slot = "Wrist", ilvl = 284, id = 54582, name = "Bracers of Fiery Night",
                    alts = {
                        { ilvl = 277, id = 50651, name = "The Lady's Brittle Bracers" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51230, name = "Sanctified Dark Coven Gloves",
                    alts = {
                        { ilvl = 277, id = 50663, name = "Gunship Captain's Mittens" },
                    },
                },
                { slot = "Waist", ilvl = 277, id = 50613, name = "Crushing Coldwraith Belt" },
                { slot = "Legs", ilvl = 277, id = 50694, name = "Plaguebringer's Stained Pants" },
                { slot = "Feet", ilvl = 277, id = 50699, name = "Plague Scientist's Boots" },
                { slot = "Ring", ilvl = 277, id = 50664, name = "Ring of Rapid Ascent",
                    alts = {
                        { ilvl = 277, id = 50714, name = "Valanar's Other Signet Ring" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50398, name = "Ashen Band of Endless Destruction" },
                { slot = "Trinket", ilvl = 277, id = 50365, name = "Phylactery of the Nameless Lich",
                    alts = {
                        { ilvl = 277, id = 50348, name = "Dislodged Foreign Object" },
                    },
                },
                { slot = "Trinket", ilvl = 284, id = 54588, name = "Charred Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 50732, name = "Bloodsurge, Kel'Thuzad's Blade of Agony" },
                { slot = "Off Hand", ilvl = 277, id = 50719, name = "Shadow Silk Spindle" },
                { slot = "Wand", ilvl = 277, id = 50684, name = "Corpse-Impaling Spike" },
            },
        },
        {
            key = "fury-warrior",
            label = "Fury Warrior",
            class = "WARRIOR",
            role = "Melee Dps",
            items = {
                { slot = "Head", ilvl = 277, id = 51227, name = "Sanctified Ymirjar Lord's Helmet" },
                { slot = "Neck", ilvl = 284, id = 54581, name = "Penumbra Pendant",
                    alts = {
                        { ilvl = 277, id = 50647, name = "Ahn'kahar Onyx Neckguard" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51229, name = "Sanctified Ymirjar Lord's Shoulderplates" },
                { slot = "Back", ilvl = 272, id = 47546, name = "Sylvanas' Cunning",
                    alts = {
                        { ilvl = 277, id = 50653, name = "Shadowvault Slayer's Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51225, name = "Sanctified Ymirjar Lord's Battleplate" },
                { slot = "Wrist", ilvl = 284, id = 54580, name = "Umbrage Armbands",
                    alts = {
                        { ilvl = 277, id = 50670, name = "Toskk's Maximized Wristguards" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 50675, name = "Aldriana's Gloves of Secrecy" },
                { slot = "Waist", ilvl = 277, id = 50620, name = "Coldwraith Links" },
                { slot = "Legs", ilvl = 277, id = 51228, name = "Sanctified Ymirjar Lord's Legplates" },
                { slot = "Feet", ilvl = 284, id = 54578, name = "Apocalypse's Advance",
                    alts = {
                        { ilvl = 277, id = 50639, name = "Blood-Soaked Saronite Stompers" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50618, name = "Frostbrood Sapphire Ring",
                    alts = {
                        { ilvl = 284, id = 54576, name = "Signet of Twilight *" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50402, name = "Ashen Band of Endless Vengeance" },
                { slot = "Trinket", ilvl = 277, id = 50363, name = "Deathbringer's Will" },
                { slot = "Trinket", ilvl = 284, id = 54590, name = "Sharpened Twilight Scale" },
                { slot = "Main Hand", ilvl = 284, id = 49623, name = "Shadowmourne" },
                { slot = "Off Hand", ilvl = 284, id = 50730, name = "Glorenzelg, High-Blade of the Silver Hand" },
                { slot = "Crossbow", ilvl = 284, id = 50733, name = "Fal'inrush, Defender of Quel'thalas" },
            },
        },
        {
            key = "protection-warrior",
            label = "Protection Warrior",
            class = "WARRIOR",
            role = "Tanks",
            items = {
                { slot = "Head", ilvl = 277, id = 50640, name = "Broken Ram Skull Helm" },
                { slot = "Neck", ilvl = 277, id = 50682, name = "Bile-Encrusted Medallion",
                    alts = {
                        { ilvl = 277, id = 50627, name = "Noose of Malachite" },
                    },
                },
                { slot = "Shoulders", ilvl = 277, id = 51224, name = "Sanctified Ymirjar Lord's Pauldrons" },
                { slot = "Back", ilvl = 277, id = 50718, name = "Royal Crimson Cloak",
                    alts = {
                        { ilvl = 264, id = 50466, name = "Sentinel's Winter Cloak" },
                    },
                },
                { slot = "Chest", ilvl = 277, id = 51220, name = "Sanctified Ymirjar Lord's Breastplate" },
                { slot = "Wrist", ilvl = 264, id = 51901, name = "Gargoyle Spit Bracers",
                    alts = {
                        { ilvl = 277, id = 50611, name = "Bracers of Dark Reckoning" },
                    },
                },
                { slot = "Hands", ilvl = 277, id = 51222, name = "Sanctified Ymirjar Lord's Handguards" },
                { slot = "Waist", ilvl = 264, id = 50991, name = "Verdigris Chain Belt",
                    alts = {
                        { ilvl = 277, id = 50691, name = "Belt of Broken Bones" },
                    },
                },
                { slot = "Legs", ilvl = 277, id = 51223, name = "Sanctified Ymirjar Lord's Legguards" },
                { slot = "Feet", ilvl = 284, id = 54579, name = "Treads of Impending Resurrection",
                    alts = {
                        { ilvl = 277, id = 50625, name = "Grinning Skull Greatboots" },
                    },
                },
                { slot = "Ring", ilvl = 277, id = 50622, name = "Devium's Eternally Cold Ring" },
                { slot = "Ring", ilvl = 277, id = 50642, name = "Juggernaut Band",
                    alts = {
                        { ilvl = 277, id = 50404, name = "Ashen Band of Endless Courage" },
                    },
                },
                { slot = "Trinket", ilvl = 277, id = 50364, name = "Sindragosa's Flawless Fang" },
                { slot = "Trinket", ilvl = 284, id = 54591, name = "Petrified Twilight Scale",
                    alts = {
                        { ilvl = 258, id = 47451, name = "Juggernaut's Vitality" },
                    },
                },
                { slot = "Main Hand", ilvl = 284, id = 50737, name = "Havoc's Call, Blade of Lordaeron Kings",
                    alts = {
                        { ilvl = 284, id = 50738, name = "Mithrios, Bronzebeard's Legacy" },
                    },
                },
                { slot = "Shield", ilvl = 277, id = 50729, name = "Icecrown Glacial Wall" },
                { slot = "Crossbow", ilvl = 264, id = 51834, name = "Dreamhunter's Carbine" },
            },
        },
    },
}
